---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
  labels:
    service: {{ .Release.Name }}-{{ .Chart.Name }}
    app: istio-auth-example
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
data:
  {{- range .Values.env }}
    {{ .name }}: {{ .value | quote }}
  {{- end }}
