---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  labels:
    service: {{ .Release.Name }}-{{ .Chart.Name }}
    app: istio-auth-example
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      service: {{ .Release.Name }}-{{ .Chart.Name }}
      app: istio-auth-example
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-{{ .Chart.Name }}
        app: istio-auth-example
        date: "{{ now | unixEpoch }}"
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-ghcr
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: {{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000

          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 5000
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # livenessProbe:
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 3
          #   httpGet:
          #     path: "/liveness"
          #     port: 5000

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
          env: # get secret env vars
            {{- range .Values.appSecrets }}
            - name: {{ .envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .keyName }}
            {{- end }}
