{{- range .Values.appSecrets }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
type: Opaque
data:
  {{ .keyName }}: {{ .value }}

{{- end }}

{{- range .Values.migrationSecrets }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-failed
type: Opaque
data:
  {{ .keyName }}: {{ .value }}

{{- end }}
