---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  labels:
    service: {{ .Release.Name }}-{{ .Chart.Name }}
    app: istio-auth-example
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  type: ClusterIP
  selector:
    service: {{ .Release.Name }}-{{ .Chart.Name }}
    app: istio-auth-example
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
