---

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "jwt-ingress-policy"
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
  - to:
    - operation:
        paths: ["/private/*"]
    when:
    - key: request.auth.claims[permissions]
      values: ["private"]
---

apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "jwt-request-authn"
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "example.com"
    jwksUri: "https://raw.githubusercontent.com/signed-long/jwks_host/main/jwks.json"