version: '3.3'
services:
  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=test_db
      - POSTGRES_DB=docker-compose
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
