version: '3.3'
services:
  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=test_db
      - POSTGRES_DB=docker-compose
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  vault:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./file:/vault/file:rw
      - ./config:/vault/config:rw