ServiceName: api-test
performDbMigration: false
env:
    - name: FLASK_APP
      value: app/__init__.py
    - name: FLASK_ENV
      value: development
image:
  repository: test-image
  tag: ghcr.io/signed-long/api_test:latest
  pullPolicy: IfNotPresent
