ServiceName: api-authentication
performDbMigration: true
image:
  tag: ghcr.io/signed-long/api_auth:b47c4e53ae370641fe8d723aab7490c8d60932a5
  pullPolicy: IfNotPresent
env:
  - name: FLASK_APP
    value: app/__init__.py
  - name: FLASK_ENV
    value: development
  - name: SQL_HOST
    value: db-postgresql-nyc1-45905-do-user-9591008-0.b.db.ondigitalocean.com
  - name: SQL_PORT
    value: 25060
  - name: DATABASE
    value: defaultdb
  - name: DATABASE_USER
    value: doadmin
  - name: ACCESS_TOKEN_EXP_SEC
    value: 900
  - name: ACCESS_TOKEN_ISS
    value: example.com
appSecrets:
  - secretName: database-password
    envName: DATABASE_PASSWORD
    type: Opaque
    keyName: password
  - secretName: access-token-private-key
    envName: ACCESS_TOKEN_PRIVATE_KEY
    type: Opaque
    keyName: private-key
migrationSecrets:
  - secretName: migration-database-password
    envName: DATABASE_PASSWORD
    type: Opaque
    keyName: password
migrationJob:
  restartPolicy: Never
