name: "api_auth"

on:
  push:
    branches:
      - main 
    # run only on changes to these paths
    paths:
      - "src/api_auth/**"
      - ".github/workflows/auth.yml"

env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
  REGISTRY: ghcr.io/signed_long
  IMAGE_NAME: api_auth

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v1

      # Build and test image using docker compose
      - name: Run tests
        run: |-
          docker-compose -f ./src/api_auth/tests/docker-compose.tests.yml up --exit-code-from api_auth --build

      # Authenticate to GHCR
      - name: 'Authenticate to GHCR'
        id: 'auth'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Push image to GHCR
      - name: Push Docker Image
        run: |
          docker tag ${{ env.IMAGE_NAME }} "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHA }}"
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHA }}"
