name: "api_auth"

on:
  push:
    branches:
      - main 
    # run only on changes to these paths
    paths:
      - "src/api_auth/**"
      - ".github/workflows/auth.yml"

env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
  REGISTRY_HOSTNAME: gcr.io

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Build and test image using docker compose
      - name: Run tests
        run: |-
          docker-compose -f ./src/api_auth/tests/docker/docker-compose.tests.yml up --exit-code-from auth_api --build

      # Authenticate to GCP
      - name: 'Authenticate to GCP'
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
          
      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: 'Login to docker with gcloud'
        run: |
          gcloud auth configure-docker -q

      # Push image to Google Container Registry
      - name: Push Docker Image
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          docker tag auth_api "$REGISTRY_HOSTNAME/istio-practice/auth_api:$TAG"
          docker push "$REGISTRY_HOSTNAME/istio-practice/auth_api:$TAG"
