name: "api_test"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    # run only on changes to these paths
    paths:
      - "src/api_test/**"
      - ".github/workflows/auth.yml"

env:
  GITHUB_SHA: ${{ github.event.pull_request.head.sha }} 
  GITHUB_REF: ${{ github.ref }} 
  REGISTRY: ghcr.io/${{ github.actor }}
  IMAGE_NAME: api_test

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      # Build and test image using docker compose
      - name: Run tests
        run: |-
          docker-compose -f ./src/${{ env.IMAGE_NAME }}/tests/docker-compose.tests.yml up --exit-code-from ${{ env.IMAGE_NAME }}_tests --build

      # Authenticate to GHCR
      - name: 'Authenticate to GHCR'
        id: 'auth'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Push image to GHCR
      - name: Push Docker Image
        run: |
          docker build src/${{ env.IMAGE_NAME }}/ --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHA }}
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"