name: Update Service Image Tag Workflow

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      service:
        required: true
        type: string

jobs:
  update-values-file:
    steps:
      - name: Update values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'file.yaml'
        propertyPath: 'file.version'
        value: v1.0.1
        commitChange: true
        updateFile: true