name: Update helm tags
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  new-image-tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files in the src folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v32
        with:
          files: |
            src/api_auth/**

      - name: Update Image Version in the related HelmChart values.yaml
        if: steps.changed-files-specific.outputs.any_changed == 'true
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: config/values.api_auth.yaml
          propertyPath: 'image.tag'
          value: ghcr.io/signed-long/api_auth:${{ github.event.pull_request.head.sha }} 
          branch: ${{ github.event.pull_request.base }} 
          targetBranch: main
          masterBranchName: main
          createPR: false
          message: 'Update Image Tag'
