ServiceName: test
hasDatabase: false
env:
    - name: FLASK_APP
      value: app/__init__.py
    - name: FLASK_ENV
      value: development
image:
  repository: test-image
  tag: gcr.io/loyal-weaver-339004/istio-practice/api_test:latest
  pullPolicy: IfNotPresent
