ServiceName: auth
hasDatabase: true

# Image info
image:
  tag: auth-image
  pullPolicy: IfNotPresent

# Env variables
env:
    - name: FLASK_APP
      value: app/__init__.py
    - name: FLASK_ENV
      value: development
    - name: SQL_HOST
      value: "34.127.116.19"
    - name: SQL_PORT
      value: 25060
    - name: DATABASE
      value: postgres
    - name: DATABASE_USER
      value: istio-example-db
    - name: ACCESS_TOKEN_EXP_SEC
      value: 900 # access token expires in 15 mins
    - name: ACCESS_TOKEN_ISS
      value: example.com

# Secrets specific to this application, to be passed in as env variables
# Must be applied manually to cluster before deployment of this service, see ../secrets/secrets.yml.example 
appSecrets:
  - secretName: database-password
    envName: DATABASE_PASSWORD
    type: Opaque
    keyName: password
  - secretName: access-token-private-key
    envName: ACCESS_TOKEN_PRIVATE_KEY
    type: Opaque
    keyName: private-key
    

# Secrets specific to this application, to be passed in as env variables
# Must be applied manually to cluster before deployment of this service, see ../secrets/secrets.yml.example 
migrationSecrets:
  - secretName: migration-database-password
    envName: DATABASE_PASSWORD
    type: Opaque
    keyName: password

migrationJob:
  # Should the job be rescheduled on the same node if it fails, or just stopped
  restartPolicy: Never
